CONFIG = {
    "WHISPER_MODEL":     "base",
    "WHISPER_COMPUTE":   "int8",
    "IDIOMA":            "es",
    "SAMPLERATE":        16000,
    "UMBRAL_VOLUMEN":    0.012,
    "SEGUNDOS_ESCUCHA":  .8,
    "SEGUNDOS_COMANDO":  3.5,
    "OLLAMA_URL":        "http://localhost:11434/api/generate",
    "OLLAMA_CHAT_URL":   "http://localhost:11434/api/chat",
    "MODELO_IA":         "llama3",
    "IA_TIMEOUT":        30,
    "IA_KEEP_ALIVE":     300,
    "FLASK_HOST":        "0.0.0.0",
    "FLASK_PORT":        5000,
    "SECRET_TOKEN":      "CAMBIA_ESTO",
    "RUTINA_BUENOS_DIAS":    "07:30",
    "RUTINA_BUENAS_NOCHES":  "23:00",
    "RUTINA_RECORDATORIO_AGUA": ["10:00", "13:00", "16:00", "19:00"],
    "SPOTIFY_CMD":      "start shell:AppsFolder\\SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify",
    "CALCULADORA_CMD":  "calc",
    "NOTAS_CMD":        "notepad",
}
